# Run AppImage electron apps on Ubuntu:
#
# [1234567:1234/123456.123456:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox
# helper binary was found, but is not configured correctly.  Rather than run
# without sandboxing I'm aborting now. You need to make sure that
# /tmp/.mount_X-XXXXX/chrome-sandbox is owned by root and has mode 4755.
# Trace/breakpoint trap (core dumped)
---
- name: Install dependencies to run Electron AppImages
  hosts: localhost

  tasks:

    - name: Install FUSE
      become: true
      ansible.builtin.apt:
        name: libfuse2t64
        state: present
      when:
        - ansible_facts.distribution == 'Ubuntu'
        - ansible_facts.distribution_version is version('24.04', '>=')

    - name: Write AppArmor file for the AppImage
      become: true
      ansible.builtin.template:
        src: templates/appimage-local.j2
        dest: /etc/apparmor.d/{{ item }}-local
        mode: '0644'
      loop:
        - zulip
      notify: Restart AppArmor service
      when: ansible_distribution == 'Ubuntu'

  handlers:

    - name: Restart AppArmor service
      become: true
      ansible.builtin.systemd_service:
        name: apparmor
        state: restarted
