---
- name: Install R and R package system dependencies
  hosts: localhost
  vars:
    r_mirror: https://cloud.r-project.org
    r_pubkey:
      Debian: 95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7
      Ubuntu: E298A3A825C0D65DFD57CBB651716619E084DAB9
    r_distro: '{{ ansible_facts.distribution_release }}'
    ver: '{{ ansible_facts.distribution_major_version }}'

  tasks:

  - name: Fetch key for R source
    become: yes
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: '{{ r_pubkey[ansible_facts.distribution] }}'

  - name: Read all Ubuntu distros for CRAN source
    community.general.read_csv:
      path: /usr/share/distro-info/ubuntu.csv
      delimiter: ','
    register: distro
    when: ansible_facts.distribution == 'Ubuntu'
    tags: distro

  - name: Lookup closest Ubuntu LTS distro name for CRAN source
    set_fact:
      r_distro: >-
        {{
        distro |
        json_query(query) |
        first() |
        json_query("[series]") |
        first()
        }}
    vars:
      query: >-
        list[?starts_with(version,'{{ ver }}')]
        .{version: version, series: series}
    when: ansible_facts.distribution == 'Ubuntu'
    tags: distro

  - name: Add R source
    become: yes
    apt_repository:
      repo: >-
        deb
        {{ r_mirror }}/bin/linux/{{ ansible_facts.distribution | lower() }}
        {{ r_distro }}-cran40/
      filename: r-project

  - name: Install packages
    become: yes
    apt:
      name:
        # The top-level R installation package.
        - r-base-dev
        # Dependencies for R packages.
        - libcairo2-dev
        - libcurl4-openssl-dev
        - libfontconfig1-dev
        - libssl-dev
        - libv8-dev
        - libxml2-dev
        - pandoc

  - name: Install obsolete packages if necessary
    become: yes
    apt:
      name:
        - pandoc-citeproc
    ignore_errors: true
