---
- name: Install Debian packages
  hosts: localhost
  vars:
    element_keyring: /usr/share/keyrings/element-io-archive-keyring.gpg
    signal_keyring: /etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg
    syncthing_keyring: /etc/apt/trusted.gpg.d/syncthing-archive-keyring.gpg
    podget_host: xm2

  tasks:

  - name: Fetch key for Syncthing source
    become: yes
    apt_key:
      url: https://syncthing.net/release-key.gpg
      keyring: '{{ syncthing_keyring }}'
    tags:
    - syncthing

  - name: Add Syncthing source
    become: yes
    apt_repository:
      repo: >-
        deb [signed-by={{ syncthing_keyring }}]
        https://apt.syncthing.net/ syncthing stable
      filename: syncthing
    tags:
    - syncthing

  - name: Fetch key for Signal source
    become: yes
    apt_key:
      url: https://updates.signal.org/desktop/apt/keys.asc
      keyring: '{{ signal_keyring }}'

  - name: Add Signal source
    become: yes
    apt_repository:
      repo: >-
        deb [arch=amd64 signed-by={{ signal_keyring }}]
        https://updates.signal.org/desktop/apt xenial main
      filename: signal

  - name: Fetch key for Element source
    become: yes
    apt_key:
      url: https://packages.element.io/debian/element-io-archive-keyring.gpg‍
      keyring: '{{ element_keyring }}'

  - name: Add Element source
    become: yes
    apt_repository:
      repo: >-
        deb [signed-by={{ element_keyring }}]
        https://packages.element.io/debian/ default main
      filename: element-io

  - name: Install packages
    become: yes
    apt:
      name:
        # LaTeX.
        - asciidoc              # for git-latexdiff
        - auctex
        - biber
        - chktex
        - dot2tex
        - latexdiff
        - latexmk
        - texlive-fonts-extra
        - texlive-latex-extra
        - texlive-science
        # C++.
        - cppcheck
        - gdb
        - strace
        - valgrind
        # Development.
        - emacs
        - emacs-common-non-dfsg
        - shellcheck
        # Utilities.
        - collectd
        - htop
        - ncdu
        - rename
        - rsync
        - scdaemon
        - smem
        - stow
        - syncthing
        - time
        - tree
        - unattended-upgrades
        # Desktop.
        - element-desktop
        - evince
        - redshift-gtk
        - gimp
        - hledger
        - hplip
        - inkscape
        - keepassxc
        - liferea
        - signal-desktop
        - thunderbird
        - xournal

  - name: Install bluetooth audio
    become: yes
    apt:
      name:
        - pulseaudio-module-bluetooth
        # Taskbar graphical utility.
        - blueman
    register: bluetooth
    notify: Restart pulseaudio
    tags: bluetooth

  - name: Install git-latexdiff
    become: yes
    shell:
      chdir: /tmp
      cmd: |
        wget https://gitlab.com/git-latexdiff/git-latexdiff/-/archive/1.6.0/git-latexdiff-1.6.0.tar.bz2
        tar -xf git-latexdiff-1.6.0.tar.bz2
        cd git-latexdiff-1.6.0
        make GIT_LATEXDIFF_VERSION=1.6.0 install
        cd ..
        rm -r git-latexdiff-1.6.0 git-latexdiff-1.6.0.tar.bz2
      creates: /usr/lib/git-core/git-latexdiff
    tags: git-latexdiff

  # https://github.com/dvehrs/podget/issues/64
  - name: Install podget with patch for m4a filenames
    become: yes
    git:
      repo: https://github.com/dvehrs/podget.git
      dest: /opt/podget
    tags: podget

  - name: Install podget config symlink
    file:
      state: link
      src: Sync/apps/podget/.podget
      dest: ~/.podget
    tags: podget

  - name: Install podget cron job
    cron:
      name: podget
      job: /home/omsai/Sync/apps/podget/podget-with-ads
      hour: '10'
      minute: '5'
      disabled: '{{ ansible_facts.hostname != podget_host }}'
    tags:
      - podget
      - podget-host

  - name: Copy Syncthing user service
    copy:
      src: /usr/lib/systemd/user/syncthing.service
      dest: /home/omsai/.config/systemd/user/

  - name: Run Syncthing
    systemd:
      name: syncthing.service
      scope: user
      enabled: true
      state: started

  handlers:

  - name: Restart pulseaudio
    shell: |
      pulseaudio --kill && sleep 10 && pulseaudio --start
    when: bluetooth.changed
    tags: bluetooth
