---
- name: Install Debian packages
  hosts: localhost
  vars:
    zfs_max: 4187689984

  tasks:

  - name: Fetch key for Ansible source
    become: yes
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367

  - name: Add Ansible source
    become: yes
    apt_repository:
      repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
      filename: ansible

  - name: Fetch key for R source
    become: yes
    apt_key:
      keyserver: keys.gnupg.net
      id: E19F5F87128899B192B1A2C2AD5F960A256A04AF

  - name: Add R source
    become: yes
    apt_repository:
      repo: deb https://cran.case.edu/bin/linux/debian buster-cran40/
      filename: r-project

  - name: Fetch key for Syncthing source
    become: yes
    apt_key:
      url: https://syncthing.net/release-key.txt

  - name: Add Syncthing source
    become: yes
    apt_repository:
      repo: deb https://apt.syncthing.net/ syncthing release
      filename: syncthing

  - name: Fetch key for Signal source
    become: yes
    apt_key:
      url: https://updates.signal.org/desktop/apt/keys.asc

  - name: Add Signal source
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
      filename: signal-xenial

  - name: Fetch key for Element source
    become: yes
    apt_key:
      url: https://packages.riot.im/debian/riot-im-archive-keyring.gpg

  - name: Add Element source
    become: yes
    apt_repository:
      repo: deb https://packages.riot.im/debian/ default main
      filename: element

  - name: Install packages
    become: yes
    apt:
      name:
        - ansible
        - ansible-lint
        # Scientific software.
        - r-base-dev
        # R package dependencies.
        - libcurl4-openssl-dev
        - libssl-dev
        - libv8-dev
        - libxml2-dev
        - pandoc
        - pandoc-citeproc
        # LaTeX.
        - auctex
        - biber
        - chktex
        - dot2tex
        - latexmk
        - texlive-fonts-extra
        - texlive-latex-extra
        - texlive-science
        # C++.
        - cppcheck
        - gdb
        - strace
        - valgrind
        # Development.
        - emacs
        - shellcheck
        # Utilities.
        - collectd
        - htop
        - ncdu
        - rename
        - rsync
        - scdaemon
        - smem
        - stow
        - syncthing
        - time
        - tree
        - unattended-upgrades
        # Desktop.
        - element-desktop
        - gtk-redshift
        - gimp
        - hledger
        - hplip
        - inkscape
        - keepassxc
        - podget
        - signal-desktop
        - thunderbird
        - xournal

  - name: Copy Syncthing user service
    copy:
      src: /usr/lib/systemd/user/syncthing.service
      dest: /home/omsai/.config/systemd/user/

  - name: Syncthing ignore ZFS snapshot directory
    lineinfile:
      create: true
      line: .zfs
      path: /home/omsai/Sync/.stignore

  - name: Run Syncthing
    systemd:
      name: syncthing.service
      scope: user
      enabled: true
      state: started

  - name: Detect running services
    service_facts:
    register: services

  - name: Detect ZFS c_max
    shell:
      cmd: sed -nr 's/^c_max .* ([[:digit:]]+)$/\1/p' /proc/spl/kstat/zfs/arcstats
      warn: false
    changed_when: false
    register: c_max
    when: '"zfs-zed.service" in ansible_facts.services'

  - name: ZFS set current c_max
    become: yes
    shell:
      cmd: 'echo {{ zfs_max }} > /sys/module/zfs/parameters/zfs_arc_max'
    when: '"zfs-zed.service" in ansible_facts.services and c_max.stdout | int != zfs_max'

  - name: ZFS set persistent c_max
    become: yes
    copy:
      dest: /etc/modprobe.d/zfs.conf
      content: |
        options zfs zfs_arc_max={{ zfs_max }}
    register: zfs_conf
    when: '"zfs-zed.service" in ansible_facts.services'

  - name: Apply zfs.conf to initramfs
    become: yes
    command: /sbin/update-initramfs -u
    when: 'zfs_conf.changed'

  - name: Enable collectd zfs_arc plugin
    become: yes
    lineinfile:
      path: /etc/collectd/collectd.conf
      validate: collectd -t %s
      regexp: '^.*(LoadPlugin zfs_arc)'
      line: '\1'
      backrefs: yes
    notify: Restart collectd
    tags: collectd

  - name: Ignore logging ZFS snapshots
    become: yes
    lineinfile:
      path: /etc/collectd/collectd.conf
      validate: collectd -t %s
      insertafter: 'FSType cgroup'
      line: '	MountPoint "snapshot"'
    notify: Restart collectd
    tags: collectd

  handlers:

  - name: Restart collectd
    become: yes
    service:
      name: collectd
      state: restarted
    tags: collectd
