---
- name: Install Debian packages
  hosts: localhost
  vars:
    zfs_max: 4187689984
    signal_keyring: /etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg

  tasks:

  - name: Fetch key for Syncthing source
    become: yes
    apt_key:
      url: https://syncthing.net/release-key.txt

  - name: Add Syncthing source
    become: yes
    apt_repository:
      repo: deb https://apt.syncthing.net/ syncthing release
      filename: syncthing

  - name: Fetch key for Signal source
    become: yes
    apt_key:
      url: https://updates.signal.org/desktop/apt/keys.asc
      keyring: '{{ signal_keyring }}'

  - name: Add Signal source
    become: yes
    apt_repository:
      repo: >-
        deb [arch=amd64 signed-by={{ signal_keyring }}]
        https://updates.signal.org/desktop/apt xenial main
      filename: signal

  - name: Fetch key for Element source
    become: yes
    apt_key:
      url: https://packages.riot.im/debian/riot-im-archive-keyring.gpg

  - name: Add Element source
    become: yes
    apt_repository:
      repo: deb https://packages.riot.im/debian/ default main
      filename: element

  - name: Install packages
    become: yes
    apt:
      name:
        # LaTeX.
        - auctex
        - biber
        - chktex
        - dot2tex
        - latexmk
        - texlive-fonts-extra
        - texlive-latex-extra
        - texlive-science
        # C++.
        - cppcheck
        - gdb
        - strace
        - valgrind
        # Development.
        - emacs
        - shellcheck
        # Utilities.
        - collectd
        - htop
        - ncdu
        - rename
        - rsync
        - scdaemon
        - smem
        - stow
        - syncthing
        - time
        - tree
        - unattended-upgrades
        # Desktop.
        - element-desktop
        - redshift-gtk
        - gimp
        - hledger
        - hplip
        - inkscape
        - keepassxc
        - liferea
        - signal-desktop
        - thunderbird
        - xournal

  # https://github.com/dvehrs/podget/issues/64
  - name: Install podget with patch for m4a filenames
    become: yes
    git:
      repo: https://github.com/dvehrs/podget.git
      dest: /opt/podget
      version: 935d0168a1cbe98bbcd27cd66a3d100533e2dd0d
    tags: podget

  - name: Copy Syncthing user service
    copy:
      src: /usr/lib/systemd/user/syncthing.service
      dest: /home/omsai/.config/systemd/user/

  - name: Run Syncthing
    systemd:
      name: syncthing.service
      scope: user
      enabled: true
      state: started

  - name: Detect running services
    service_facts:
    register: services

  - name: Detect ZFS c_max
    shell:
      cmd: sed -nr 's/^c_max .* ([[:digit:]]+)$/\1/p' /proc/spl/kstat/zfs/arcstats
      warn: false
    changed_when: false
    register: c_max
    when: '"zfs-zed.service" in ansible_facts.services'

  - name: ZFS set current c_max
    become: yes
    shell:
      cmd: 'echo {{ zfs_max }} > /sys/module/zfs/parameters/zfs_arc_max'
    when: '"zfs-zed.service" in ansible_facts.services and c_max.stdout | int != zfs_max'

  - name: ZFS set persistent c_max
    become: yes
    copy:
      dest: /etc/modprobe.d/zfs.conf
      content: |
        options zfs zfs_arc_max={{ zfs_max }}
    register: zfs_conf
    when: '"zfs-zed.service" in ansible_facts.services'

  - name: Apply zfs.conf to initramfs
    become: yes
    command: /sbin/update-initramfs -u
    when: 'zfs_conf.changed'

  - name: Enable collectd zfs_arc plugin
    become: yes
    lineinfile:
      path: /etc/collectd/collectd.conf
      validate: collectd -t %s
      regexp: '^.*(LoadPlugin zfs_arc)'
      line: '\1'
      backrefs: yes
    notify: Restart collectd
    tags: collectd

  - name: Allowlist ZFS locations
    become: yes
    replace:
      path: /etc/collectd/collectd.conf
      validate: collectd -t %s
      # This regex pattern replaces the block using non-greedy behavior per
      # https://stackoverflow.com/a/7124976 and
      # https://serverfault.com/a/966435
      regexp: '^<Plugin df>[\s\S]+?(?=</Plugin>)'
      replace: |
        <Plugin df>
        	MountPoint "/home/omsai"
        	MountPoint "/home/omsai/Sync"
    notify: Restart collectd
    tags: collectd

  handlers:

  - name: Restart collectd
    become: yes
    service:
      name: collectd
      state: restarted
    tags: collectd
