---
- name: Install Debian packages
  hosts: localhost
  vars:
    signal_keyring: /etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg

  tasks:

  - name: Fetch key for Syncthing source
    become: yes
    apt_key:
      url: https://syncthing.net/release-key.txt

  - name: Add Syncthing source
    become: yes
    apt_repository:
      repo: deb https://apt.syncthing.net/ syncthing release
      filename: syncthing

  - name: Fetch key for Signal source
    become: yes
    apt_key:
      url: https://updates.signal.org/desktop/apt/keys.asc
      keyring: '{{ signal_keyring }}'

  - name: Add Signal source
    become: yes
    apt_repository:
      repo: >-
        deb [arch=amd64 signed-by={{ signal_keyring }}]
        https://updates.signal.org/desktop/apt xenial main
      filename: signal

  - name: Fetch key for Element source
    become: yes
    apt_key:
      url: https://packages.riot.im/debian/riot-im-archive-keyring.gpg

  - name: Add Element source
    become: yes
    apt_repository:
      repo: deb https://packages.riot.im/debian/ default main
      filename: element

  - name: Install packages
    become: yes
    apt:
      name:
        # LaTeX.
        - auctex
        - biber
        - chktex
        - dot2tex
        - latexmk
        - texlive-fonts-extra
        - texlive-latex-extra
        - texlive-science
        # C++.
        - cppcheck
        - gdb
        - strace
        - valgrind
        # Development.
        - emacs
        - shellcheck
        # Utilities.
        - collectd
        - htop
        - ncdu
        - rename
        - rsync
        - scdaemon
        - smem
        - stow
        - syncthing
        - time
        - tree
        - unattended-upgrades
        # Desktop.
        - element-desktop
        - redshift-gtk
        - gimp
        - hledger
        - hplip
        - inkscape
        - keepassxc
        - liferea
        - signal-desktop
        - thunderbird
        - xournal

  # https://github.com/dvehrs/podget/issues/64
  - name: Install podget with patch for m4a filenames
    become: yes
    git:
      repo: https://github.com/dvehrs/podget.git
      dest: /opt/podget
      version: 935d0168a1cbe98bbcd27cd66a3d100533e2dd0d
    tags: podget

  - name: Copy Syncthing user service
    copy:
      src: /usr/lib/systemd/user/syncthing.service
      dest: /home/omsai/.config/systemd/user/

  - name: Run Syncthing
    systemd:
      name: syncthing.service
      scope: user
      enabled: true
      state: started
