---
- name: Install Debian packages
  hosts: localhost

  tasks:

  - name: Fetch key for Ansible source
    become: yes
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367

  - name: Add Ansible source
    become: yes
    apt_repository:
      repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
      filename: ansible

  - name: Fetch key for R source
    become: yes
    apt_key:
      keyserver: keys.gnupg.net
      id: E19F5F87128899B192B1A2C2AD5F960A256A04AF

  - name: Add R source
    become: yes
    apt_repository:
      repo: deb https://cloud.r-project.org/bin/linux/debian buster-cran40/
      filename: r-project

  - name: Fetch key for Syncthing source
    become: yes
    apt_key:
      url: https://syncthing.net/release-key.txt

  - name: Add Syncthing source
    become: yes
    apt_repository:
      repo: deb https://apt.syncthing.net/ syncthing release
      filename: syncthing

  - name: Install packages
    become: yes
    apt:
      name:
        - ansible
        - ansible-lint
        # Scientific software.
        - r-base-dev
        # R package dependencies.
        - libcurl4-openssl-dev
        - libssl-dev
        - libxml2-dev
        - pandoc
        # LaTeX.
        - auctex
        - biber
        - chktex
        - latexmk
        - texlive-fonts-extra
        - texlive-latex-extra
        # C++.
        - cppcheck
        - gdb
        - strace
        - valgrind
        # Development.
        - emacs
        - emacs-common-non-dfsg
        - shellcheck
        # Utilities.
        - collectd
        - htop
        - ncdu
        - rename
        - rsync
        - scdaemon
        - stow
        - syncthing
        - time
        - tree
        - unattended-upgrades
        # Desktop.
        - gtk-redshift
        - gimp
        - hplip
        - inkscape
        - keepassxc
        - podget
        - thunderbird

  - name: Copy Syncthing user service
    copy:
      src: /usr/lib/systemd/user/syncthing.service
      dest: /home/omsai/.config/systemd/user/

  - name: Syncthing ignore ZFS snapshot directory
    lineinfile:
      create: true
      line: .zfs
      path: /home/omsai/Sync/.stignore

  - name: Run Syncthing
    systemd:
      name: syncthing.service
      scope: user
      enabled: true
      state: started
