# Remap numpad / - + to volume mute, down, and up, respectively for keyboards
# missing native volume control.
---

- name: Create startup script to xmodmap numpad to volume keys
  hosts: localhost
  vars:
    src_xmodmap: templates/xmodmap-volume.j2
    src_xmodmapd: templates/xmodmap-volumed.j2
    src_systemd_service: templates/volume-keys.service.j2
    file_xmodmap: '{{ ansible_env.HOME }}/.xmodmap-volume'
    file_xmodmapd: '{{ file_xmodmap }}d'
    file_systemd_service: |-
      {{ ansible_env.HOME }}/.config/systemd/user/volume-keys.service

  tasks:

    - name: Write scripts
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: '{{ item.mode }}'
      loop:
        - src: '{{ src_xmodmap }}'
          dest: '{{ file_xmodmap }}'
          mode: '0755'
        - src: '{{ src_xmodmapd }}'
          dest: '{{ file_xmodmapd }}'
          mode: '0755'
        - src: '{{ src_systemd_service }}'
          dest: '{{ file_systemd_service }}'
          mode: '0644'
      notify: Restart volume-keys

    - name: Add systemd service that runs after login
      ansible.builtin.systemd_service:
        name: volume-keys
        scope: user
        enabled: true
      notify: Restart volume-keys

  handlers:

    - name: Restart volume-keys
      ansible.builtin.systemd_service:
        name: volume-keys
        scope: user
        state: restarted
