# https://github.com/ProtonVPN/linux-cli

- name: Install VPN CLI and watchdog
  hosts: localhost
  vars:
    protonvpn_repo: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/
    prefix: /usr
    pcli: '{{ prefix }}/bin/protonvpn-cli'
    pcli_watchdog: '{{ prefix }}/bin/protonvpn-watchdog'

  tasks:

    - name: List all protonvpn .deb files
      uri:
        url: '{{ protonvpn_repo }}'
        return_content: yes
      register: files_url
      tags: release

    - name: Identify the lastest protonvpn release
      set_fact:
        protonvpn_deb: >-
          {{
          files_url.content |
          regex_findall("protonvpn-stable-release[a-z0-9_.-]+[.]deb") |
          last()
          }}
        cacheable: yes
      tags: release

    - name: Add protonvpn source
      become: yes
      apt:
        deb: '{{ protonvpn_repo }}{{ protonvpn_deb }}'
      register: repo

    - name: Install protonvpn-cli
      become: yes
      apt:
        name: protonvpn
        update_cache: '{{ repo.changed }}'
      notify: Restart VPN watchdog service if necessary

    - name: Add VPN watchdog executable
      become: yes
      template:
        src: templates/protonvpn-watchdog.j2
        dest: '{{ pcli_watchdog }}'
        mode: +x
      notify: Restart VPN watchdog service if necessary
      tags: watchdog

    - name: Add VPN watchdog service
      become: yes
      template:
        src: templates/protonvpn-watchdog.service.j2
        dest: /etc/systemd/user/protonvpn-watchdog.service
      notify: Restart VPN watchdog service if necessary
      tags: watchdog

    - name: Enable and start VPN watchdog service
      systemd:
        name: protonvpn-watchdog
        scope: user
        state: started
        enabled: yes
        daemon_reload: yes
      register: just_started
      notify: Restart VPN watchdog service if necessary
      tags: watchdog

  handlers:

    - name: Restart VPN watchdog service if necessary
      systemd:
        name: protonvpn-watchdog
        scope: user
        state: restarted
        daemon_reload: yes
