# https://github.com/ProtonVPN/protonvpn-cli-ng

- name: Install VPN
  hosts: localhost
  become: true
  vars:
    prefix: /opt/protonvpn-cli
    protonvpn: '{{ prefix }}/bin/protonvpn'

  tasks:

    - name: Install protonvpn-cli dependencies
      apt:
        name:
          - dialog
          - openvpn
          - python-pexpect     # For ansible expect module.
          - python3-pip
          - python3-setuptools
          - python3-venv

    - name: Install protonvpn-cli
      pip:
        name: protonvpn-cli
        virtualenv_command: /usr/bin/python3 -m venv
        virtualenv: '{{ prefix }}'
        state: latest

    - name: Fail if manual configuration is necessary
      expect:
        command: '{{ protonvpn }} init'
        responses:
          overwrite: n
      changed_when: false
      # Ignore return code 2.
      register: init
      failed_when: '"overwrite" not in init.stdout'

    - name: Add VPN service file
      template:
        src: templates/protonvpn.service.j2
        dest: /etc/systemd/system/protonvpn.service
      notify: Restart VPN service

    - name: Disable OpenVPN service
      service:
        name: openvpn
        state: stopped
        enabled: no

    - name: Enable and Start VPN service
      service:
        name: protonvpn
        state: started
        enabled: yes

  handlers:
  - name: Restart VPN service
    service:
      name: protonvpn
      state: restarted
